	0	1	2	3	4
1	XXX	egor	XXX	XXX	XXX
2	XXX	XXX	XXX	XXX	XXX
3	XXX	XXX	XXX	XXX	XXX
4	XXX	XXX	XXX	XXX	XXX
5	XXX	XXX	XXX	XXX	XXX
6	XXX	XXX	XXX	XXX	XXX
7	XXX	XXX	XXX	XXX	XXX
8	XXX	XXX	XXX	XXX	XXX
9	XXX	XXX	XXX	XXX	XXX
10	XXX	XXX	XXX	XXX	XXX
